### ISSUE TITLE
Getting Agency By Coordinates

### ISSUE THREAD

**Issue by dus-d** [jpod32/pulsepoint#1]
Nice to see a project like this pop-up.  I wrote something similar a few years back that was in a very early prototype state, but I wanted to share some things I found out.

First, the endpoint at "/DB/gabc.php" can take query string parameters of "lat" and "lng" for Latitude and Longitude, respectively. (e.g., "/DB/gabc.php?lat=33.99553&lng=-118.240144"  What you get in return is an array of Agencies with their display name and some other info.  For some reason this doesn't return the actual AgencyID, but it gives a different property just called "id".  This endpoint needs the same decryption.

If you hit the endpoint at "/DB/GeolocationAgency.php" and pass the previously obtained "id", you get more Agency info including the "agencyId".  (e.g., "DB/GeolocationAgency.php?id=400").

Not sure why they have it setup like this, but there's a lot of good info there, even a polygon for the coverage area if you wanna project this onto Google Maps or something.

**Comment by Podskio** [comment]
This is very helpful, thank you! I'll definitely work on adding these features in. I wish they just had a public API without all the obfuscation 😁

**Comment by dus-d** [comment]
Yeah I left a nice comment in my codebase for the secret as "obfuscation != security".

I had emailed them years back about doing this and they kept referencing their Terms of Use since this is basically scraping.  Before all these changes it used to be a much simpler, easier to use API that there's a few abandoned repos for.

Another interesting scraping project if you're interested is for CrimeMapping.  Not live data but similar.

**Comment by Podskio** [comment]
> Another interesting scraping project if you're interested is for CrimeMapping. Not live data but similar.

I'll check it out!

**Comment by Podskio** [comment]
Implemented in v1.5.0
